version: '3.1'

services:
  nest-app:
    build: .
    env_file: .env.db
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    secrets:
      - source: db_credentials
        target: db_credentials
    deploy:
      replicas: 1

  postgres:
    image: postgres:latest
    env_file: .env.db
    secrets:
      - db_credentials
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

secrets:
  db_credentials:
    file: .env.db

